title: Data Architect
description: A blog for my projects at Datastax
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
url: "https://ds-steven-matison.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jemoji